apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yrcd13qcd-nodejs 
  janus-idp.io/tekton: yrcd13qcd-nodejs
  backstage.io/kubernetes-id: yrcd13qcd-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yrcd13qcd-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml