apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yrcd13qcd-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yrcd13qcd-nodejs 
  name: yrcd13qcd-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: yrcd13qcd-nodejs 
